const INTERFACE_ADDRESS = 'http://localhost:7071';
const SYSTEM_GATEWAY = '';
const INTERFACE_VERSION = '/api/v1';
export const SystemConstant = Object.freeze({
  LOCAL_STORAGE_PREFIX: 'xdht-disease-',
  SESSION_STORAGE_PREFIX: 'xdht-disease-',
  // 系统配置
  GET_TOKEN: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/login/createToken',
  EDIT_PASSWORD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/editPassword',
  // 用户配置
  USER_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysUser/userPage',
  USER_ADD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysUser/add',
  USER_EDIT: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysUser/update',
  USER_DEL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysUser/delete',
  USER_DETAIL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysUser/detail',
  // 角色配置
  ROLE_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysRole/rolePage',
  ROLE_ADD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysRole/add',
  ROLE_EDIT: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysRole/update',
  ROLE_DEL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysRole/delete',
  ROLE_DETAIL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysRole/detail',

  // 菜单配置
  MENU_PAGE_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenu/menuPage',
  MENU_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenu/menusList',
  MENU_ADD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenu/add',
  MENU_EDIT: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenu/update',
  MENU_DEL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenu/delete',
  MENU_DETAIL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenRECORD_SCENE_LIST:u/detail',

  // 调查表配置
  RECORD_SCENE_PAGE_LIST : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/recordPage',
  RECORD_SCENE_LIST : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/recordList',
  RECORD_SCENE_ADD : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/add',
  RECORD_SCENE_ADDALL : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/addAll',
  RECORD_SCENE_EDIT : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/update',
  RECORD_SCENE_DEL : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/delete',
  RECORD_SCENE_DETAIL : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/detail',

  // 调查问卷配置
  QUESTION_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysQuestionnaire/recordList',
  QUESTION_ALL_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysQuestionnaire/listAll',
  QUESTION_ADD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysQuestionnaire/add',
  QUESTION_DEl: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysQuestionnaire/delete',
  QUESTION_EDIT: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysQuestionnaire/update',
  QUESTION_DETAIL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysQuestionnaire/detail',

  // 问卷调查状态配置
  RECORD_SCENE_QUESTION_ADD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScenQuestionnaire/add',

  // 公司配置
  COMPANY_ALL_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysCompany/listAll',

  // 部门配置
  OFFICE_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysCompanyOffice/queryList',

  // 员工配置
  EMPLOYEE_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysEmployee/employeeList',
});
