const INTERFACE_ADDRESS = 'http://localhost:7071';
const SYSTEM_GATEWAY = '';
const INTERFACE_VERSION = '/api/v1';
export const SystemConstant = Object.freeze({
  LOCAL_STORAGE_PREFIX: 'xdht-disease-',
  SESSION_STORAGE_PREFIX: 'xdht-disease-',
  // 系统配置
  GET_TOKEN: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/login/createToken',
  EDIT_PASSWORD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/editPassword',
  // 用户配置
  USER_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysUser/userPage',
  USER_ADD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysUser/add',
  USER_EDIT: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysUser/update',
  USER_DEL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysUser/delete',
  USER_DETAIL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysUser/detail',
  // 角色配置
  ROLE_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysRole/rolePage',
  ROLE_ADD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysRole/add',
  ROLE_EDIT: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysRole/update',
  ROLE_DEL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysRole/delete',
  ROLE_DETAIL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysRole/detail',

  // 菜单配置
  MENU_PAGE_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenu/menuPage',
  MENU_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenu/menusList',
  MENU_ADD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenu/add',
  MENU_EDIT: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenu/update',
  MENU_DEL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenu/delete',
  MENU_DETAIL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysMenRECORD_SCENE_LIST:u/detail',

  // 职业卫生现场调查记录表配置
  RECORD_SCENE_PAGE_LIST : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/pageList',
  RECORD_SCENE_ADD : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/add',
  RECORD_SCENE_EDIT : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/update',
  RECORD_SCENE_DEL : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/delete',
  RECORD_SCENE_DETAIL : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordScene/detail',

  // 职业卫生调查内容
  QUESTION_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysQuestionnaire/list',

  // 公司配置
  COMPANY_PAGE_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysCompany/pageList',
  COMPANY_ALL_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysCompany/listAll',
  COMPANY_ADD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysCompany/add',
  COMPANY_EDIT: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysCompany/update',
  COMPANY_DEL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysCompany/delete',
  COMPANY_DETAIL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysCompany/detail',

  // 部门配置
  OFFICE_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysCompanyOffice/queryList',

  // 员工配置
  COMPANY_EMPLOYEE_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/sysEmployee/companyEmployeeList',

  // 建设项目(预评价)配置
  PRE_EVALUATION_PROJECT_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordPreEvaluationProject/listAll',
  // 建设项目概况调查表（预评价） 配置
  PRE_EVALUATION_PAGE_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordPreEvaluation/pageList',
  PRE_EVALUATION_ADD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordPreEvaluation/add',
  PRE_EVALUATION_EDIT: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordPreEvaluation/update',
  PRE_EVALUATION_DEL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordPreEvaluation/delete',
  PRE_EVALUATION_DETAIL : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordPreEvaluation/detail',

  // 建设项目概况调查表（控制效果评价）配置
  CONTROL_EFFECT_PAGE_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordControlEffect/pageList',
  CONTROL_EFFECT_ADD: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordControlEffect/add',
  CONTROL_EFFECT_EDIT: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordControlEffect/update',
  CONTROL_EFFECT_DEL: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordControlEffect/delete',
  CONTROL_EFFECT_DETAIL : INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordControlEffect/detail',
  // 建设项目配置（控制效果评价）
  CONTROL_EFFECT_PROJECT_LIST: INTERFACE_ADDRESS + SYSTEM_GATEWAY + INTERFACE_VERSION + '/recordControlEffectProject/list',
});
